name: aoc
channels:
    - conda-forge

dependencies:
    - pandas
    - numpy
    - matplotlib
    - seaborn
    - scipy
    - pytest
    - pytest-watch
    - numexpr
    - pip
    - pip:
        - advent-of-code-data
        - loguru
